name: Integration Tests

on:
  push:
    branches:
      - main
      - add-some-tests
  pull_request:
    branches:
      - main

jobs:
  run-integration-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        override: true

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y libssl-dev pkg-config

    - name: Build project
      run: cargo build

    - name: Run integration tests
      run: cargo test --test space_cli_tests
